name: CI Backend Gestão RH

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest black

      - name: Verificar formatação do código com Black
        run: black --check .

      - name: Rodar linter com Flake8
        run: flake8 .

      - name: Rodar Testes com Pytest
        run: pytest

      - name: Build da Imagem Docker
        run: docker build . --file Dockerfile --tag gestao-rh:${{ github.sha }}